packages:
  - apps/*
  - packages/*

catalog:
  "@vitest/browser-playwright": 4.1.11
  "@types/node": 24.13.3
  "@vitest/coverage-v8": 4.1.11
  playwright: 1.62.1
  typescript: 6.0.3
  vitest: 4.1.11
  zod: 4.5.4
