export const NATIVE_MESSAGE_HEADER_BYTES = 4 as const;
export const DEFAULT_NATIVE_MESSAGE_MAX_FRAME_BYTES = 1_048_576 as const;
export const DEFAULT_NATIVE_MESSAGE_MAX_BUFFERED_BYTES = 2_097_160 as const;
export const DEFAULT_NATIVE_MESSAGE_MAX_QUEUED_BYTES = 2_097_160 as const;
export const DEFAULT_NATIVE_MESSAGE_MAX_QUEUED_MESSAGES = 32 as const;
